### ISSUE TITLE
How to logout of a POD rather than retain cached login

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid-auth#1]
For the example app I login as charlieb, then logout and try to login as another user, it goes back to charlieb.

Even exit and restart retains charlieb login. How to actually "logout" of charlib.

**Comment by anushkavidanage** [comment]
Does this happen with the web app or the Android app? Pushed some new changes to the example app and checked with Android and Google Chrome. The logout works fine for me now. Please check and let me know you are still facing this issue.

**Comment by gjwgit** [comment]
I was testing with the Linux desktop app.

Logout now works.

I do see the following errors:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method closeWebView on channel plugins.flutter.io/url_launcher)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      closeWebView (package:url_launcher/url_launcher.dart:143:10)
<asynchronous suspension>
```

Pops up regularly on login

**Comment by anushkavidanage** [comment]
This has been fixed in the new version https://pub.dev/packages/solid_auth
