### ISSUE TITLE
Pop up small window in non_web desktop or web apps

### ISSUE THREAD

**Issue by Zheyuan-Robert-Xu** [anusii/solid-auth#3]
In web version, the login page works as the small popup window.
In mobile or desktop app, it opens a new whole browser screen. It would be better to open a small popup screen like the web version.

![image](https://user-images.githubusercontent.com/79696631/158941309-c7b1aeb1-79b5-4bfb-92bd-e67241bd879d.png)

**Comment by anushkavidanage** [comment]
This needs to be addressed on the server side.

**Comment by anushkavidanage** [comment]
Closing the issue as this is a server side thing
