### ISSUE TITLE
The closeInAppWebView() is required for android app

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid-auth#5]
## Description

The recent 0.1.6 release removed closeInAppWebView() since it is not supported on the Linux desktop. However, when running the app on the android simulator, after Authorising the "Login successful. You can now close this window!" message is all that is shown on the screen with no apparent way to close the in-app webview. Thus the app is stuck at that point and the only work around is to kill the app and revert to the 0.1.5 release

## Why

So that the latest release can work on multiple platforms.

## Closing Criteria

- [x] No undefined closeInAppWebView() on Linux desktop
- [x] No blocked "Login successful" on Android app

**Comment by anushkavidanage** [comment]
This issue has been fixed in the new release 0.1.7
