### ISSUE TITLE
SOLID_AUTH: Is there a reason it is not web compatible?

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid-auth#7]
![Image](https://github.com/anusii/solid-auth/assets/1681429/54ff5002-b772-4fe3-a4b1-68c3f70982e9)

**Comment by gjwgit** [comment]
updated and pending analysis.,

**Comment by anushkavidanage** [comment]
![Image](https://github.com/anusii/solid-auth/assets/81279146/5f8e90c8-d4ce-4277-b987-c658166173ff)

**Comment by anushkavidanage** [comment]
![Image](https://github.com/anusii/solid-auth/assets/81279146/7ff50055-9721-4260-b66f-43f71444ab63)
